// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmjvwzckcslwychoortj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtanZ3emNrY3Nsd3ljaG9vcnRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjUwODgsImV4cCI6MjA2NTc0MTA4OH0.uv5_if0mKHhBGUC31PbAfs95nNCqL2tUf5LeGOVzzfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);